export const SOCIAL = [
  {
    name: "Toastmasters",
    outcomes: [
      "You will have created a health plan",
      "You will know the food pyramid",
      "You will know why eat nutrient is important",
    ],
    book: "Food Rules: An Eater's Manual",
    project: "",
    Mentor: "Tosha Lillywhite",
    Weeks: [],
  },
  {
    name: "Language",
    outcomes: [
      "You will have created a health plan",
      "You will know the food pyramid",
      "You will know why eat nutrient is important",
    ],
    book: "Food Rules: An Eater's Manual",
    project: "",
    Mentor: "Tosha Lillywhite",
    Weeks: [],
  },
  {
    name: "Service",
    outcomes: ["You will be able to identify 12 of the major world religions"],
    book: "The 12 major world religions",
    project: "",
    Mentor: "Cody Lillywhite",
    Weeks: [],
  },
  {
    name: "Teamwork",
    outcomes: ["You will be able to identify 12 of the major world religions"],
    book: "The 12 major world religions",
    project: "",
    Mentor: "Cody Lillywhite",
    Weeks: [],
  },
  {
    name: "Ettiquette",
    outcomes: ["You will be able to identify 12 of the major world religions"],
    book: "The 12 major world religions",
    project: "",
    Mentor: "Cody Lillywhite",
    Weeks: [],
  },
  {
    name: "Making Friends",
    outcomes: ["You will be able to identify 12 of the major world religions"],
    book: "The 12 major world religions",
    project: "",
    Mentor: "Cody Lillywhite",
    Weeks: [],
  },
  {
    name: "Family",
  },
];
